config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  scope "/admin" do
  	get '/add_player', to: 'players#new'
  	post '/add_player', to: 'players#create'
  	resources :players
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
	mount_uploader :avatar, AvatarUploader
	validates :name, presence: true, length: { maximum: 50 }
	validate :avatar_size

	private
		def avatar_size
			if avatar.size > 5.megabytes
				errors.add(:avatar, "should be less than 5MB")
			end
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
  	# @players = Player.paginate(page: params[:page], per_page: 1)
  	@players = Player.all
  end

  def new
  	@player = Player.new
  end

  def create
  	@player = Player.new(player_params)
  	if @player.save
  		flash[:success] = "The Player successfully created!"
  		redirect_to players_url
  	else
  		render 'new'
  	end
  end

  def edit
  	@player = Player.find(params[:id])
  end

  def update
  	@player = Player.find(params[:id])
  	if @player.update_attributes(player_params)
  		flash[:success] = "The Player information successfully updated."
  		redirect_to players_url
  	else
  		render 'edit'
  	end
  end


  private
  	def player_params
  		params.require(:player).permit(:name, :avatar)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nijmegenceria</title>
    <%= csrf_meta_tags %>
		<%= stylesheet_link_tag 'https://fonts.googleapis.com/icon?family=Material+Icons' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <main>
      <div class="container">
        <% flash.each do |message_type, message| %>
          <%= javascript_tag do %>
            $(function(){Materialize.toast('<%= message %>', 5000, 'rounded');});
          <% end %>
        <% end %>
        <%= yield %>
        <%= render "shared/modal_login" %>
      </div>
    </main>
    <%= render 'shared/footer' %>
    <%= javascript_tag do %>
      $(document).ready(function(){
        $('.button-collapse').sideNav();
      });
    <% end %>
    <%= debug(params) if Rails.env.development? %>
  </body>

</html>

app/views/pages/home.html.erb
<div class="row">
	<div class="col s12 center">
		<h4> Games' Logs </h4>
		<p class="center-align light">Sorry, currently there are no game logs available.</p>
	</div>
</div>
<div class="divider"></div>

app/views/players/_player.html.erb
<li class="collection-item avatar">
  <%= image_tag(player.avatar? ? player.avatar.url : "default_profile.png", class: "circle") %>
  <span class="title"><%= player.name %></span>
  <p><%= pluralize(0, 'game') %> played.
  <div class="fixed-action-btn horizontal click-to-toggle secondary-content" style="bottom: 45px; right: 24px;">
    <a class="btn-floating btn-large teal" id="menu_edit">
      <i class="material-icons">menu</i>
    </a>
    <ul>
      <li><a class="btn-floating red"><i class="material-icons">delete_sweep</i></a></li>
      <li>
        <%= link_to(edit_player_path(player), class: "btn-floating blue") do %>
          <i class="material-icons">mode_edit</i>
        <% end %>
      </li>
    </ul>
	</div>
</li>
			    

app/views/players/edit.html.erb
<div class="row">
  <div class="col m10 offset-m1 s12">
    <h3 class="center-align">Add Player</h2>
    <div class="row">
    	<%= render 'shared/error_messages' %>
      <%= form_for @player, html: { class: "col s12", multipart: true } do |f| %>
        <div class="row">
          <div class="input-field col m12 s12">
            <%= f.text_field(:name, type: "text") %>
						<%= f.label :name %>
          </div>
        </div>
        <div class="row">
          <div class="col m4">
            <%= image_tag(@player.avatar? ? @player.avatar.url : "default_profile.png", class: "responsive-img z-depth-3") %>
          </div>
          <div class="col m8">
            <div class="file-field input-field">
				      <div class="btn">
				        <span>Photo</span>
                <%= f.file_field :avatar, accept: 'image/jpeg,image/jpg,image/png' %>
				      </div>
				      <div class="file-path-wrapper">
                <input class="file-path validate" type="text" placeholder="Upload a photo">
              </div>
			    	</div>
          </div>
        </div>
        <div class="row">
          <div class="col m12">
           <p class="right-align">
           <%= f.button 'Save Change', class: "btn btn-large waves-effect waves-light" %>
         	 </p>
          </div>
        </div>
        <% end %>
    </div>
  </div>
</div>


<script type="text/javascript">
  $('#player_avatar').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/players/index.html.erb
<div class="row">
  <div class="col m10 offset-m1 s12">
    <h3 class="center-align">List of All Players</h2>
    <ul class="collection">
    	<%= render @players %>	
  	</ul>
  </div>
</div>

app/views/players/new.html.erb
  <div class="row">
  <div class="col m10 offset-m1 s12">
    <h3 class="center-align">Add Player</h2>
    <div class="row">
    	<%= render 'shared/error_messages' %>
      <%= form_for @player, html: { class: "col s12", multipart: true }, url: add_player_path do |f| %>
        <div class="row">
          <div class="input-field col m12 s12">
            <%= f.text_field(:name, type: "text") %>
						<%= f.label :name %>
          </div>
        </div>
        <div class="row">
          <div class="file-field input-field">
			      <div class="btn">
			        <span>Photo</span>
              <%= f.file_field :avatar, accept: 'image/jpeg,image/jpg,image/png' %>
			      </div>
			      <div class="file-path-wrapper">
              <input class="file-path validate" type="text" placeholder="Upload a photo">
            </div>
		    	</div>
        </div>
        <div class="row">
          <div class="col m12 s12">
           <p class="right-align">
           <%= f.button 'Save', class: "btn btn-large waves-effect waves-light" %>
         	 </p>
          </div>
        </div>
        <% end %>
    </div>
  </div>
</div>


<script type="text/javascript">
  $('#player_avatar').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/shared/_error_messages.html.erb
<% if @player.errors.any? %>
	<div class="row">
        <div class="col m6 offset-m3 s12">
          <div class="card green lighten-4">
            <div class="card-content red-text text-darken-4">
              <p>Please fix <%= pluralize(@player.errors.count, "error") %>:</p>
              <div class="container">
              <ul class="browser-default">
              	<% @player.errors.full_messages.each do |msg| %>
      						<li><%= msg %></li>
    						<% end %>
    					</ul>
    					</div>
            </div>
          </div>
        </div>
      </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="page-footer">
  <div class="footer-copyright">
    <div class="container">
    	© 2016 MD Taufan
    	<span class="right">
    		Made with
    		<i class="tiny material-icons teal-text text-lighten-3">favorite</i>
    		in Nijmegen
    	</span>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
	<div class="navbar-fixed">
		<nav>
		  <div class="nav-wrapper">
		    <%= link_to("Nijmegen Ceria", root_path, class: "brand-logo") %>
		    <a href="#" data-activates="slide-out" class="button-collapse"><i class="material-icons">menu</i></a>
		    <ul class="right hide-on-med-and-down">
		      <li><a class= "modal-trigger" href="#modalLogin"><i class="material-icons right">perm_identity</i>Login Admin</a></li>
		    </ul>
		    <ul class="side-nav" id="slide-out">
        	<li><a class= "modal-trigger" href="#modalLogin"><i class="material-icons right">perm_identity</i>Login Admin</a></li>
      	</ul>
		  </div>
		</nav>
	</div>
</header>

app/views/shared/_modal_login.html.erb
<div id="modalLogin" class="modal">
  <div class="modal-content">
  	<h4 class="center-align">Log in Admin</h4>
  	<form class="col s12">
    	<div class="row">
        <div class="input-field col s12">
        	<i class="material-icons prefix">contact_mail</i>
          <input id="email" type="email" class="validate">
          <label for="email">Email</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
        	<i class="material-icons prefix">vpn_key</i>
          <input id="password" type="password" class="validate">
          <label for="password">Password</label>
        </div>
      </div>
      <div class="row right-align">
      	<button class="btn waves-effect waves-light" type="submit" name="action">Login</button>
      </div>
    </form>
  </div>
</div>
<%= javascript_tag do %>
  $(document).ready(function(){
    $('.modal-trigger').leanModal();
  });
<% end %>